### ISSUE TITLE
NO LICENSE ?

### ISSUE THREAD

**Issue by iitaku** [kdaiki211/Excel2Html#9]
We'd like to import Exel2Html to our projects, so need to clarify the LICENSE. 
What's your plan ?

**Comment by kdaiki211** [comment]
Thank you for your request.

I'll consider a license of the Excel2Html.
Give me some time, please.

**Comment by kdaiki211** [comment]
Added LICENSE.txt. We determined to use the MIT license.
Check for 93088e682060ed72c647ad62835afdc232e66ee1.
